services:
  - type: web
    name: collab-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm ci --omit=dev
    startCommand: cd server && npm run start:render
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: collab-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: CLIENT_URL
        value: https://your-frontend.onrender.com
      - key: DOCKER_ENABLED
        value: false

  - type: web
    name: collab-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://your-backend.onrender.com
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false

databases:
  - name: collab-mongodb
    databaseName: collaborative_coding
    user: admin
