name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: collabquest_test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install server dependencies
      run: cd server && npm ci
    
    - name: Install client dependencies
      run: cd client && npm ci
    
    - name: Run server linting
      run: cd server && npm run lint
      continue-on-error: true
    
    - name: Run client linting
      run: cd client && npm run lint
      continue-on-error: true
    
    - name: Run server tests
      run: cd server && npm test
      env:
        CI: true
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/collabquest_test
        JWT_SECRET: test-jwt-secret
        SUPABASE_URL: https://test.supabase.co
        SUPABASE_ANON_KEY: test-anon-key
      continue-on-error: true
    
    - name: Run client tests
      run: cd client && npm test -- --watchAll=false
      env:
        CI: true
      continue-on-error: true
    
    - name: Build client application
      run: cd client && npm run build
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        fail_ci_if_error: false
      continue-on-error: true
